services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app_db"]
      interval: 5s
      retries: 5
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 5
  
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"

  cassandra:
    image: cassandra:5.0
    environment:
      CASSANDRA_CLUSTER_NAME: "dev-cluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: "pokemoningestor-cassandra-1"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      retries: 10
      start_period: 60s

  cassandra_init:
    image: cassandra:5.0
    depends_on:
      cassandra:
        condition: "service_healthy"
    entrypoint: >
      bash -c "
      cqlsh pokemoningestor-cassandra-1 -e 
      \"create keyspace if not exists pokemon
        with replication = {'class': 'SimpleStrategy', 'replication_factor': 3};\"
      "
  
  crawler:
    build: ./app/gengar
    container_name: scrapy_crawler
    depends_on:
      - postgres
      - elasticsearch
      - cassandra
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/app_db
      ELASTICSEARCH_URL: http://elasticsearch:9200
      CASSANDRA_URL: http://cassandra:9042
    volumes:
      - ./app/gengar:/app
    working_dir: /app
    entrypoint: ["tail", "-f", "/dev/null"]
  
  api:
    build: ./app/charmander
    container_name: api_backend
    depends_on:
      postgres:
        condition: "service_healthy"
      elasticsearch:
        condition: "service_healthy"
      cassandra:
        condition: "service_healthy"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/app_db
      ELASTICSEARCH_URL: http://elasticsearch:9200
      CASSANDRA_HOSTS: pokemoningestor-cassandra-1,pokemoningestor-cassandra-2,pokemoningestor-cassandra-3
      CASSANDRA_PORT: 9042
    volumes:
      - ./app:/app
    working_dir: /app/charmander
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  python-runner:
    build: ./app/charmander
    container_name: python_runner
    depends_on:
      - postgres
      - elasticsearch
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/app_db
      ELASTICSEARCH_URL: http://elasticsearch:9200
      CASSANDRA_HOSTS: pokemoningestor-cassandra-1,pokemoningestor-cassandra-2,pokemoningestor-cassandra-3
      CASSANDRA_PORT: 9042
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
  es_data:
